### ISSUE TITLE
404 on all pages

### ISSUE THREAD

**Issue by dtg57** [damianmoore/xr-brighton-website#45]
Hi @damianmoore - I've been managing the content on the XR Brighton site for the past few months. In the last week or so the site has been down, displaying 404s on every page including admin pages. I'm happy to take a look at it myself, if you're happy to give me SSH access or whatever is needed - just let me know!

**Comment by damianmoore** [comment]
Hi @dtg57, Apologies for this and thanks for notifying. I think I restarted the server and this Docker container didn't come up.

I've now added `restart: always` to the service in Docker Compose and added a monitor for it in Uptime Robot so it shouldn't happen again.

**Comment by dtg57** [comment]
> Hi @dtg57, Apologies for this and thanks for notifying. I think I restarted the server and this Docker container didn't come up.
> 
> I've now added `restart: always` to the service in Docker Compose and added a monitor for it in Uptime Robot so it shouldn't happen again.

That's great - thanks for your quick response 😄
